-- This script will be generated by reading the automations data
-- First, let's truncate the table to start fresh (optional - remove if you want to keep existing data)
-- TRUNCATE TABLE automations;

-- Note: This is a template. The actual inserts will be generated from the TypeScript data.
-- Run this from the application code to populate all 2000+ automations.
